default['java']['package'] = 'java-1.8.0-openjdk'
default['tomcat']['download_url'] = 'https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.69/bin/apache-tomcat-8.5.69.tar.gz'
default['tomcat']['version'] = '8.5.69'
# default['tomcat']['download_url'] = 'https://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.52/bin/apache-tomcat-9.0.52.tar.gz'
# default['tomcat']['version'] = '9.0.52'
